// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sohesepxpbkepobzigyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvaGVzZXB4cGJrZXBvYnppZ3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDQ2MzUsImV4cCI6MjA3MTE4MDYzNX0.DiBk6Qb3C7DsU8x6Bum2IH0rUzWoKFQ7w7d7TXNZxac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});